CREATE OR REPLACE VIEW wycieczki_osoby
  AS
    SELECT w.ID_WYCIECZKI, w.NAZWA, w.KRAJ, w.DATA, o.IMIE, o.NAZWISKO, r.STATUS
    FROM WYCIECZKI w
           JOIN REZERWACJE r ON w.ID_WYCIECZKI = r.ID_WYCIECZKI
           JOIN OSOBY o ON r.ID_OSOBY = o.ID_OSOBY;

CREATE OR REPLACE VIEW wycieczki_osoby_potwierdzone
  AS
    SELECT w.KRAJ, w.DATA, w.NAZWA, o.IMIE, o.NAZWISKO, r.STATUS
    FROM WYCIECZKI w
           JOIN REZERWACJE r on w.ID_WYCIECZKI = r.ID_WYCIECZKI
           JOIN OSOBY o on r.ID_OSOBY = o.ID_OSOBY
    WHERE r.STATUS in ('P', 'Z');

CREATE OR REPLACE VIEW wycieczki_przyszle
  AS
    SELECT w.KRAJ, w.DATA, w.NAZWA, o.IMIE, o.NAZWISKO, r.STATUS
    FROM WYCIECZKI w
           JOIN REZERWACJE r on w.ID_WYCIECZKI = r.ID_WYCIECZKI
           JOIN OSOBY o on r.ID_OSOBY = o.ID_OSOBY
    WHERE w.DATA > SYSDATE;

CREATE OR REPLACE VIEW wycieczki_miejsca
  AS
    SELECT w.KRAJ, w.DATA, w.NAZWA, w.LICZBA_MIEJSC, w.LICZBA_MIEJSC - COUNT(r.NR_REZERWACJI) AS LICZBA_WOLNYCH_MIEJSC
    FROM WYCIECZKI w
           LEFT JOIN REZERWACJE r on w.ID_WYCIECZKI = r.ID_WYCIECZKI
    WHERE r.STATUS in ('P', 'Z', 'N')
    GROUP BY w.ID_WYCIECZKI, w.KRAJ, w.DATA, w.NAZWA, w.LICZBA_MIEJSC;

CREATE OR REPLACE VIEW dostepne_wycieczki
  AS
    SELECT w.KRAJ, w.DATA, w.NAZWA, w.LICZBA_MIEJSC, w.LICZBA_MIEJSC - COUNT(r.NR_REZERWACJI) AS LICZBA_WOLNYCH_MIEJSC
    FROM WYCIECZKI w
           LEFT JOIN REZERWACJE r on w.ID_WYCIECZKI = r.ID_WYCIECZKI
    WHERE r.STATUS in ('P', 'Z', 'N')
    GROUP BY w.ID_WYCIECZKI, w.KRAJ, w.DATA, w.NAZWA, w.LICZBA_MIEJSC
    HAVING w.LICZBA_MIEJSC - COUNT(r.NR_REZERWACJI) > 0;

CREATE OR REPLACE VIEW rezerwacje_do_anulowania
  AS
    SELECT r.NR_REZERWACJI, r.ID_WYCIECZKI, r.ID_OSOBY, r.STATUS
    FROM REZERWACJE r
           JOIN WYCIECZKI w on r.ID_WYCIECZKI = w.ID_WYCIECZKI
    WHERE r.STATUS = 'N'
      AND SYSDATE + 7 > w.DATA

CREATE OR REPLACE VIEW wycieczki_miejsca_2
  AS
    SELECT w.KRAJ, w.DATA, w.NAZWA, w.LICZBA_MIEJSC, w.LICZBA_WOLNYCH_MIEJSC
    FROM WYCIECZKI w
           LEFT JOIN REZERWACJE r on w.ID_WYCIECZKI = r.ID_WYCIECZKI
    WHERE r.STATUS in ('P', 'Z', 'N')
    GROUP BY w.ID_WYCIECZKI, w.KRAJ, w.DATA, w.NAZWA, w.LICZBA_MIEJSC, w.LICZBA_WOLNYCH_MIEJSC;

CREATE OR REPLACE VIEW dostepne_wycieczki_2
  AS
    SELECT w.KRAJ, w.DATA, w.NAZWA, w.LICZBA_MIEJSC, w.LICZBA_WOLNYCH_MIEJSC
    FROM WYCIECZKI w
           LEFT JOIN REZERWACJE r on w.ID_WYCIECZKI = r.ID_WYCIECZKI
    WHERE r.STATUS in ('P', 'Z', 'N')
    GROUP BY w.ID_WYCIECZKI, w.KRAJ, w.DATA, w.NAZWA, w.LICZBA_MIEJSC, w.LICZBA_WOLNYCH_MIEJSC
    HAVING w.LICZBA_WOLNYCH_MIEJSC > 0;